version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    # - "./nginx/default.php.conf:/etc/nginx/conf.d/default.conf"
    # - "./nginx/default.proxy.conf:/etc/nginx/conf.d/default.conf"
    # - "./nginx/default.path.conf:/etc/nginx/conf.d/default.conf"
    # - "./nginx/default.domain.conf:/etc/nginx/conf.d/default.conf"
    - "./webroot:/var/www/html"
  php:
    image: php:fpm
    volumes:
    - "./webroot:/var/www/html"
  whoami:
    image: traefik/whoami
